services:
  # ===========================
  # Postgres Database
  # ===========================
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5433:5432"

  # ===========================
  # Backend
  # ===========================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: hackx-backend:latest
    container_name: backend
    env_file:
      - ./backend/.env.prod   # contains DATABASE_URL like postgresql://user:pass@db:5432/mujhackx?schema=public
    depends_on:
      - db
    ports:
      - "5000:5000"
      - "9000:9000"
    networks:
      - app-network

  # ===========================
  # Frontend
  # ===========================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: hackx-frontend:latest
    container_name: frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
